import csv
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

class AlertFormatter:
    def format(self, alert_data):
        raise NotImplementedError("Format method must be implemented by subclasses.")

class CSVAlertFormatter(AlertFormatter):
    def format(self, alert_data):
        fieldnames = ['alert_type', 'severity', 'src_ip', 'details', 'description', 'count']
        descriptions = {
            "ARP Spoofing Detected": "ARP spoofing involves sending fake ARP messages over a local area network. This technique exploits the lack of authentication in the ARP protocol to link an attacker's MAC address with the IP address of a legitimate computer or server on the network.",
            "Unusual ARP Response Frequency": "An unusually high frequency of ARP responses may indicate an ongoing ARP spoofing attack, where an attacker attempts to intercept, modify, or stop data in transit.",
            "Multiple MACs Detected": "Detecting multiple MAC addresses for the same IP could indicate ARP cache poisoning, a technique used to attack a network by associating the attacker’s MAC address with the IP address of a legitimate computer or server.",
            "Potential ARP Cache Poisoning": "This alert indicates possible ARP cache poisoning, where multiple MAC addresses are associated with a single IP, potentially redirecting traffic to an attacker.",
            "DHCP Spoofing": "DHCP spoofing occurs when an attacker sends fake DHCP responses to clients, assigning them an IP address controlled by the attacker. This can lead to man-in-the-middle attacks or network disruption.",
            "Suspicious Activity": "This general alert indicates suspicious network activity that may not fit a specific attack pattern but warrants further investigation.",
            "DNS Spoofing": "DNS spoofing, or DNS cache poisoning, involves introducing corrupt DNS cache information to redirect traffic to malicious sites, facilitating phishing attacks or spreading malware.",
            "DNS Tunneling": "DNS tunneling involves encoding the data of other programs or protocols in DNS queries and responses. It can be used for malicious purposes, including data exfiltration.",
            "DDoS Attack": "A Distributed Denial of Service (DDoS) attack aims to overwhelm a targeted server, service, or network by flooding it with Internet traffic, rendering it unavailable to users.",
            "DoS Attack": "A Denial of Service (DoS) attack aims to shut down a machine or network, making it inaccessible to its intended users by overwhelming it with traffic.",
            "MITM Detected": "Man-In-The-Middle (MITM) attacks involve an attacker secretly relaying and possibly altering the communication between two parties who believe they are directly communicating with each other.",
            "Port Scanning Detected": "Port scanning is a method used by attackers to discover vulnerable services that they can potentially exploit on a networked computer.",
            "Malicious Destination IP Detected": "The system has identified a connection attempt to an IP address that is known for suspicious activities, as listed in our threat intelligence database from IOCs Feeds Platform.",
            "Malicious Source IP Detected": "A network connection was initiated from an IP address recognized for harmful activities, as listed in our threat intelligence database from IOCs Feeds Platform.",
            "Frequent DNS Queries": "A high number of DNS queries in a short period may suggest suspicious activity, such as DNS tunneling or data exfiltration.",
            "High Traffic Anomaly": "A significant increase in network traffic could indicate a potential attack, such as a DDoS, or a misconfigured network device.",
            "High Entropy DGA Domain Detected": "A domain generated by a Domain Generation Algorithm (DGA) has been detected, often used by malware to evade detection by frequently changing its domain names.",
            "HTTP Flood Detected": "An HTTP flood attack aims to overwhelm a server with HTTP requests, causing a denial of service to legitimate users.",
            "ICMP Tunneling Detected": "ICMP tunneling is a method of using ICMP packets to covertly transmit data, potentially indicating data exfiltration or covert communication channels.",
            "Frequent ICMP Packets": "An unusual number of ICMP packets could indicate network scanning or ICMP tunneling, which is often used for reconnaissance or covert communication.",
            "Unusual SMB Authentication Frequency": "A high frequency of SMB authentication attempts may suggest a brute force attack, where an attacker is attempting to guess passwords to gain access to a network.",
            "Multiple SMB Authentication Attempts": "Multiple failed SMB authentication attempts could indicate a brute force attack, where an attacker is trying to gain unauthorized access by guessing passwords.",
            "Multiple SMB Session IDs": "Multiple SMB session IDs from a single IP may indicate suspicious activity, such as an attempt to evade detection by using multiple sessions.",
            "Possible TLS MITM Detected": "Potential man-in-the-middle activity detected on a TLS connection, which could compromise the confidentiality and integrity of the encrypted communication.",
            "LLMNR Poisoning Detected": "Link-Local Multicast Name Resolution (LLMNR) poisoning is an attack where an attacker responds to LLMNR requests intended for other hosts, potentially redirecting traffic to malicious sites.",
            "NBT-NS Poisoning Detected": "NetBIOS Name Service (NBT-NS) poisoning is similar to LLMNR poisoning, where an attacker responds to NBT-NS requests, potentially redirecting traffic to malicious sites.",
            "IP Spoofing Detected": "IP spoofing involves sending packets with a false source IP address, potentially used to bypass IP-based authentication or to disguise the origin of an attack.",
            "P2P Communication Detected": "Peer-to-peer (P2P) communication detected on the network, which could be used for legitimate purposes or for malicious activities such as file sharing of illegal content.",
            "MAC Flooding Detected": "MAC flooding involves sending numerous packets to a switch, each with a different source MAC address, potentially causing the switch to enter a fail-open mode and broadcast traffic to all ports.",
            "Frequent MAC Changes Detected": "Frequent changes in MAC addresses on a network interface may indicate spoofing or a scanning tool, potentially used to evade detection or to perform reconnaissance.",
            "IP Null Scan Detected": "An IP Null scan is a type of network scan where the attacker sends packets with no TCP flags set, potentially used to identify open ports by observing the target's response.",
            "RST/FIN Flood Detected": "RST/FIN flooding involves sending a large number of TCP RST or FIN packets to a target, potentially disrupting legitimate TCP connections or exhausting resources.",
            "Possible DNS over HTTPS (DoH) Detected": "This detection indicates potential use of DNS over HTTPS (DoH), which could be used to bypass traditional DNS monitoring mechanisms and obscure DNS queries from security tools.",
            "HTTP/S Beaconing Detected": "HTTP/S beaconing involves periodic communication between a compromised device and a command and control server, often indicating malware activity and the presence of an advanced persistent threat.",
            "Tor Exit Node Traffic Detected": "Traffic to or from known Tor exit nodes has been detected, which may indicate anonymized communication often associated with malicious activity, such as browsing the dark web or bypassing censorship.",
            "Newly Registered Domain Detected": "A connection to a domain that was recently registered has been detected, which can be indicative of phishing or command-and-control (C2) domains used by attackers to evade detection.",
            "Suspicious User-Agent Detected": "A user-agent string that is uncommon or known to be associated with malicious activity has been detected in network traffic, potentially indicating the use of automated tools or malware.",
            "Suspicious Hostname Detected": "A hostname in network traffic that appears unusual or is associated with known threats has been detected, warranting further investigation for potential malicious activity.",
            "Suspicious Geo-Location Detected": "Network traffic originating from or destined to an unusual or high-risk geographic location has been detected, suggesting potential malicious activity or policy violations."
        }

        severity_levels = {
            'ARP Spoofing Detected': 'Medium',
            'Unusual ARP Response Frequency': 'Low',
            'Multiple MACs Detected': 'Low',
            'Potential ARP Cache Poisoning': 'Medium',
            'DHCP Spoofing': 'Medium',
            'Suspicious Activity': 'Low',
            'DNS Spoofing': 'Medium',
            'DNS Tunneling': 'Medium',
            'DDoS Attack': 'Critical',
            'DoS Attack': 'Critical',
            'MITM Detected': 'Critical',
            'Port Scanning Detected': 'Medium',
            'Malicious Destination IP Detected': 'High',
            'Malicious Source IP Detected': 'High',
            'Frequent DNS Queries': 'Low',
            'High Traffic Anomaly': 'High',
            'High Entropy DGA Domain Detected': 'High',
            'HTTP Flood Detected': 'High',
            'ICMP Tunneling Detected': 'High',
            'Frequent ICMP Packets': 'Low',
            'Unusual SMB Authentication Frequency': 'Medium',
            'Multiple SMB Authentication Attempts': 'Low',
            'Multiple SMB Session IDs': 'Low',
            'Possible TLS MITM Detected': 'Critical',
            'LLMNR Poisoning Detected': 'Medium',
            'NBT-NS Poisoning Detected': 'Medium',
            'IP Spoofing Detected': 'High',
            'P2P Communication Detected': 'Low',
            'MAC Flooding Detected': 'Medium',
            'Frequent MAC Changes Detected': 'Low',
            'IP Null Scan Detected': 'Medium',
            'RST/FIN Flood Detected': 'High'
        }

        alert_data['description'] = descriptions.get(alert_data['alert_type'], "No specific description available for this alert type.")
        alert_data['severity'] = severity_levels.get(alert_data['alert_type'], "Unknown")

        with open('alerts.csv', mode='a', newline='') as file:
            writer = csv.DictWriter(file, fieldnames=fieldnames)
            if file.tell() == 0:  # File is empty, write header
                writer.writeheader()
            writer.writerow(alert_data)

class JSONAlertFormatter(AlertFormatter):
    def format(self, alert_data):
        descriptions = {
            "ARP Spoofing Detected": "ARP spoofing involves sending fake ARP messages over a local area network. This technique exploits the lack of authentication in the ARP protocol to link an attacker's MAC address with the IP address of a legitimate computer or server on the network.",
            "Unusual ARP Response Frequency": "An unusually high frequency of ARP responses may indicate an ongoing ARP spoofing attack, where an attacker attempts to intercept, modify, or stop data in transit.",
            "Multiple MACs Detected": "Detecting multiple MAC addresses for the same IP could indicate ARP cache poisoning, a technique used to attack a network by associating the attacker’s MAC address with the IP address of a legitimate computer or server.",
            "Potential ARP Cache Poisoning": "This alert indicates possible ARP cache poisoning, where multiple MAC addresses are associated with a single IP, potentially redirecting traffic to an attacker.",
            "DHCP Spoofing": "DHCP spoofing occurs when an attacker sends fake DHCP responses to clients, assigning them an IP address controlled by the attacker. This can lead to man-in-the-middle attacks or network disruption.",
            "Suspicious Activity": "This general alert indicates suspicious network activity that may not fit a specific attack pattern but warrants further investigation.",
            "DNS Spoofing": "DNS spoofing, or DNS cache poisoning, involves introducing corrupt DNS cache information to redirect traffic to malicious sites, facilitating phishing attacks or spreading malware.",
            "DNS Tunneling": "DNS tunneling involves encoding the data of other programs or protocols in DNS queries and responses. It can be used for malicious purposes, including data exfiltration.",
            "DDoS Attack": "A Distributed Denial of Service (DDoS) attack aims to overwhelm a targeted server, service, or network by flooding it with Internet traffic, rendering it unavailable to users.",
            "DoS Attack": "A Denial of Service (DoS) attack aims to shut down a machine or network, making it inaccessible to its intended users by overwhelming it with traffic.",
            "MITM Detected": "Man-In-The-Middle (MITM) attacks involve an attacker secretly relaying and possibly altering the communication between two parties who believe they are directly communicating with each other.",
            "Port Scanning Detected": "Port scanning is a method used by attackers to discover vulnerable services that they can potentially exploit on a networked computer.",
            "Malicious Destination IP Detected": "The system has identified a connection attempt to an IP address that is known for suspicious activities, as listed in our threat intelligence database from IOCs Feeds Platform.",
            "Malicious Source IP Detected": "A network connection was initiated from an IP address recognized for harmful activities, as listed in our threat intelligence database from IOCs Feeds Platform.",
            "Frequent DNS Queries": "A high number of DNS queries in a short period may suggest suspicious activity, such as DNS tunneling or data exfiltration.",
            "High Traffic Anomaly": "A significant increase in network traffic could indicate a potential attack, such as a DDoS, or a misconfigured network device.",
            "High Entropy DGA Domain Detected": "A domain generated by a Domain Generation Algorithm (DGA) has been detected, often used by malware to evade detection by frequently changing its domain names.",
            "HTTP Flood Detected": "An HTTP flood attack aims to overwhelm a server with HTTP requests, causing a denial of service to legitimate users.",
            "ICMP Tunneling Detected": "ICMP tunneling is a method of using ICMP packets to covertly transmit data, potentially indicating data exfiltration or covert communication channels.",
            "Frequent ICMP Packets": "An unusual number of ICMP packets could indicate network scanning or ICMP tunneling, which is often used for reconnaissance or covert communication.",
            "Unusual SMB Authentication Frequency": "A high frequency of SMB authentication attempts may suggest a brute force attack, where an attacker is attempting to guess passwords to gain access to a network.",
            "Multiple SMB Authentication Attempts": "Multiple failed SMB authentication attempts could indicate a brute force attack, where an attacker is trying to gain unauthorized access by guessing passwords.",
            "Multiple SMB Session IDs": "Multiple SMB session IDs from a single IP may indicate suspicious activity, such as an attempt to evade detection by using multiple sessions.",
            "Possible TLS MITM Detected": "Potential man-in-the-middle activity detected on a TLS connection, which could compromise the confidentiality and integrity of the encrypted communication.",
            "LLMNR Poisoning Detected": "Link-Local Multicast Name Resolution (LLMNR) poisoning is an attack where an attacker responds to LLMNR requests intended for other hosts, potentially redirecting traffic to malicious sites.",
            "NBT-NS Poisoning Detected": "NetBIOS Name Service (NBT-NS) poisoning is similar to LLMNR poisoning, where an attacker responds to NBT-NS requests, potentially redirecting traffic to malicious sites.",
            "IP Spoofing Detected": "IP spoofing involves sending packets with a false source IP address, potentially used to bypass IP-based authentication or to disguise the origin of an attack.",
            "P2P Communication Detected": "Peer-to-peer (P2P) communication detected on the network, which could be used for legitimate purposes or for malicious activities such as file sharing of illegal content.",
            "MAC Flooding Detected": "MAC flooding involves sending numerous packets to a switch, each with a different source MAC address, potentially causing the switch to enter a fail-open mode and broadcast traffic to all ports.",
            "Frequent MAC Changes Detected": "Frequent changes in MAC addresses on a network interface may indicate spoofing or a scanning tool, potentially used to evade detection or to perform reconnaissance.",
            "IP Null Scan Detected": "An IP Null scan is a type of network scan where the attacker sends packets with no TCP flags set, potentially used to identify open ports by observing the target's response.",
            "RST/FIN Flood Detected": "RST/FIN flooding involves sending a large number of TCP RST or FIN packets to a target, potentially disrupting legitimate TCP connections or exhausting resources.",
            "Possible DNS over HTTPS (DoH) Detected": "This detection indicates potential use of DNS over HTTPS (DoH), which could be used to bypass traditional DNS monitoring mechanisms and obscure DNS queries from security tools.",
            "HTTP/S Beaconing Detected": "HTTP/S beaconing involves periodic communication between a compromised device and a command and control server, often indicating malware activity and the presence of an advanced persistent threat.",
            "Tor Exit Node Traffic Detected": "Traffic to or from known Tor exit nodes has been detected, which may indicate anonymized communication often associated with malicious activity, such as browsing the dark web or bypassing censorship.",
            "Newly Registered Domain Detected": "A connection to a domain that was recently registered has been detected, which can be indicative of phishing or command-and-control (C2) domains used by attackers to evade detection.",
            "Suspicious User-Agent Detected": "A user-agent string that is uncommon or known to be associated with malicious activity has been detected in network traffic, potentially indicating the use of automated tools or malware.",
            "Suspicious Hostname Detected": "A hostname in network traffic that appears unusual or is associated with known threats has been detected, warranting further investigation for potential malicious activity.",
            "Suspicious Geo-Location Detected": "Network traffic originating from or destined to an unusual or high-risk geographic location has been detected, suggesting potential malicious activity or policy violations."
        }
        
        severity_levels = {
            'ARP Spoofing Detected': 'Medium',
            'Unusual ARP Response Frequency': 'Low',
            'Multiple MACs Detected': 'Low',
            'Potential ARP Cache Poisoning': 'Medium',
            'DHCP Spoofing': 'Medium',
            'Suspicious Activity': 'Low',
            'DNS Spoofing': 'Medium',
            'DNS Tunneling': 'Medium',
            'DDoS Attack': 'Critical',
            'DoS Attack': 'Critical',
            'MITM Detected': 'Critical',
            'Port Scanning Detected': 'Medium',
            'Malicious Destination IP Detected': 'High',
            'Malicious Source IP Detected': 'High',
            'Frequent DNS Queries': 'Low',
            'High Traffic Anomaly': 'High',
            'High Entropy DGA Domain Detected': 'High',
            'HTTP Flood Detected': 'High',
            'ICMP Tunneling Detected': 'High',
            'Frequent ICMP Packets': 'Low',
            'Unusual SMB Authentication Frequency': 'Medium',
            'Multiple SMB Authentication Attempts': 'Low',
            'Multiple SMB Session IDs': 'Low',
            'Possible TLS MITM Detected': 'Critical',
            'LLMNR Poisoning Detected': 'Medium',
            'NBT-NS Poisoning Detected': 'Medium',
            'IP Spoofing Detected': 'High',
            'P2P Communication Detected': 'Low',
            'MAC Flooding Detected': 'Medium',
            'Frequent MAC Changes Detected': 'Low',
            'IP Null Scan Detected': 'Medium',
            'RST/FIN Flood Detected': 'High'
        }

        alert_data['description'] = descriptions.get(alert_data['alert_type'], "No specific description available for this alert type.")
        alert_data['severity'] = severity_levels.get(alert_data['alert_type'], "Unknown")

        with open('alerts.json', mode='a') as file:
            json.dump(alert_data, file, indent=4)
            file.write('\n')  # For readability

class PDFAlertFormatter(AlertFormatter):
    def format(self, alert_data):
        filename = f"alert_{alert_data['src_ip']}_{alert_data['alert_type']}.pdf"
        doc = SimpleDocTemplate(filename, pagesize=letter)
        styles = getSampleStyleSheet()
        
        content = []

        descriptions = {
            "ARP Spoofing Detected": "ARP spoofing involves sending fake ARP messages over a local area network. This technique exploits the lack of authentication in the ARP protocol to link an attacker's MAC address with the IP address of a legitimate computer or server on the network.",
            "Unusual ARP Response Frequency": "An unusually high frequency of ARP responses may indicate an ongoing ARP spoofing attack, where an attacker attempts to intercept, modify, or stop data in transit.",
            "Multiple MACs Detected": "Detecting multiple MAC addresses for the same IP could indicate ARP cache poisoning, a technique used to attack a network by associating the attacker’s MAC address with the IP address of a legitimate computer or server.",
            "Potential ARP Cache Poisoning": "This alert indicates possible ARP cache poisoning, where multiple MAC addresses are associated with a single IP, potentially redirecting traffic to an attacker.",
            "DHCP Spoofing": "DHCP spoofing occurs when an attacker sends fake DHCP responses to clients, assigning them an IP address controlled by the attacker. This can lead to man-in-the-middle attacks or network disruption.",
            "Suspicious Activity": "This general alert indicates suspicious network activity that may not fit a specific attack pattern but warrants further investigation.",
            "DNS Spoofing": "DNS spoofing, or DNS cache poisoning, involves introducing corrupt DNS cache information to redirect traffic to malicious sites, facilitating phishing attacks or spreading malware.",
            "DNS Tunneling": "DNS tunneling involves encoding the data of other programs or protocols in DNS queries and responses. It can be used for malicious purposes, including data exfiltration.",
            "DDoS Attack": "A Distributed Denial of Service (DDoS) attack aims to overwhelm a targeted server, service, or network by flooding it with Internet traffic, rendering it unavailable to users.",
            "DoS Attack": "A Denial of Service (DoS) attack aims to shut down a machine or network, making it inaccessible to its intended users by overwhelming it with traffic.",
            "MITM Detected": "Man-In-The-Middle (MITM) attacks involve an attacker secretly relaying and possibly altering the communication between two parties who believe they are directly communicating with each other.",
            "Port Scanning Detected": "Port scanning is a method used by attackers to discover vulnerable services that they can potentially exploit on a networked computer.",
            "Malicious Destination IP Detected": "The system has identified a connection attempt to an IP address that is known for suspicious activities, as listed in our threat intelligence database from IOCs Feeds Platform.",
            "Malicious Source IP Detected": "A network connection was initiated from an IP address recognized for harmful activities, as listed in our threat intelligence database from IOCs Feeds Platform.",
            "Frequent DNS Queries": "A high number of DNS queries in a short period may suggest suspicious activity, such as DNS tunneling or data exfiltration.",
            "High Traffic Anomaly": "A significant increase in network traffic could indicate a potential attack, such as a DDoS, or a misconfigured network device.",
            "High Entropy DGA Domain Detected": "A domain generated by a Domain Generation Algorithm (DGA) has been detected, often used by malware to evade detection by frequently changing its domain names.",
            "HTTP Flood Detected": "An HTTP flood attack aims to overwhelm a server with HTTP requests, causing a denial of service to legitimate users.",
            "ICMP Tunneling Detected": "ICMP tunneling is a method of using ICMP packets to covertly transmit data, potentially indicating data exfiltration or covert communication channels.",
            "Frequent ICMP Packets": "An unusual number of ICMP packets could indicate network scanning or ICMP tunneling, which is often used for reconnaissance or covert communication.",
            "Unusual SMB Authentication Frequency": "A high frequency of SMB authentication attempts may suggest a brute force attack, where an attacker is attempting to guess passwords to gain access to a network.",
            "Multiple SMB Authentication Attempts": "Multiple failed SMB authentication attempts could indicate a brute force attack, where an attacker is trying to gain unauthorized access by guessing passwords.",
            "Multiple SMB Session IDs": "Multiple SMB session IDs from a single IP may indicate suspicious activity, such as an attempt to evade detection by using multiple sessions.",
            "Possible TLS MITM Detected": "Potential man-in-the-middle activity detected on a TLS connection, which could compromise the confidentiality and integrity of the encrypted communication.",
            "LLMNR Poisoning Detected": "Link-Local Multicast Name Resolution (LLMNR) poisoning is an attack where an attacker responds to LLMNR requests intended for other hosts, potentially redirecting traffic to malicious sites.",
            "NBT-NS Poisoning Detected": "NetBIOS Name Service (NBT-NS) poisoning is similar to LLMNR poisoning, where an attacker responds to NBT-NS requests, potentially redirecting traffic to malicious sites.",
            "IP Spoofing Detected": "IP spoofing involves sending packets with a false source IP address, potentially used to bypass IP-based authentication or to disguise the origin of an attack.",
            "P2P Communication Detected": "Peer-to-peer (P2P) communication detected on the network, which could be used for legitimate purposes or for malicious activities such as file sharing of illegal content.",
            "MAC Flooding Detected": "MAC flooding involves sending numerous packets to a switch, each with a different source MAC address, potentially causing the switch to enter a fail-open mode and broadcast traffic to all ports.",
            "Frequent MAC Changes Detected": "Frequent changes in MAC addresses on a network interface may indicate spoofing or a scanning tool, potentially used to evade detection or to perform reconnaissance.",
            "IP Null Scan Detected": "An IP Null scan is a type of network scan where the attacker sends packets with no TCP flags set, potentially used to identify open ports by observing the target's response.",
            "RST/FIN Flood Detected": "RST/FIN flooding involves sending a large number of TCP RST or FIN packets to a target, potentially disrupting legitimate TCP connections or exhausting resources.",
            "Possible DNS over HTTPS (DoH) Detected": "This detection indicates potential use of DNS over HTTPS (DoH), which could be used to bypass traditional DNS monitoring mechanisms and obscure DNS queries from security tools.",
            "HTTP/S Beaconing Detected": "HTTP/S beaconing involves periodic communication between a compromised device and a command and control server, often indicating malware activity and the presence of an advanced persistent threat.",
            "Tor Exit Node Traffic Detected": "Traffic to or from known Tor exit nodes has been detected, which may indicate anonymized communication often associated with malicious activity, such as browsing the dark web or bypassing censorship.",
            "Newly Registered Domain Detected": "A connection to a domain that was recently registered has been detected, which can be indicative of phishing or command-and-control (C2) domains used by attackers to evade detection.",
            "Suspicious User-Agent Detected": "A user-agent string that is uncommon or known to be associated with malicious activity has been detected in network traffic, potentially indicating the use of automated tools or malware.",
            "Suspicious Hostname Detected": "A hostname in network traffic that appears unusual or is associated with known threats has been detected, warranting further investigation for potential malicious activity.",
            "Suspicious Geo-Location Detected": "Network traffic originating from or destined to an unusual or high-risk geographic location has been detected, suggesting potential malicious activity or policy violations."
        }
        severity_levels = {
            'ARP Spoofing Detected': 'Medium',
            'Unusual ARP Response Frequency': 'Low',
            'Multiple MACs Detected': 'Low',
            'Potential ARP Cache Poisoning': 'Medium',
            'DHCP Spoofing': 'Medium',
            'Suspicious Activity': 'Low',
            'DNS Spoofing': 'Medium',
            'DNS Tunneling': 'Medium',
            'DDoS Attack': 'Critical',
            'DoS Attack': 'Critical',
            'MITM Detected': 'Critical',
            'Port Scanning Detected': 'Medium',
            'Malicious Destination IP Detected': 'High',
            'Malicious Source IP Detected': 'High',
            'Frequent DNS Queries': 'Low',
            'High Traffic Anomaly': 'High',
            'High Entropy DGA Domain Detected': 'High',
            'HTTP Flood Detected': 'High',
            'ICMP Tunneling Detected': 'High',
            'Frequent ICMP Packets': 'Low',
            'Unusual SMB Authentication Frequency': 'Medium',
            'Multiple SMB Authentication Attempts': 'Low',
            'Multiple SMB Session IDs': 'Low',
            'Possible TLS MITM Detected': 'Critical',
            'LLMNR Poisoning Detected': 'Medium',
            'NBT-NS Poisoning Detected': 'Medium',
            'IP Spoofing Detected': 'High',
            'P2P Communication Detected': 'Low',
            'MAC Flooding Detected': 'Medium',
            'Frequent MAC Changes Detected': 'Low',
            'IP Null Scan Detected': 'Medium',
            'RST/FIN Flood Detected': 'High'
        }


        alert_data['description'] = descriptions.get(alert_data['alert_type'], "No specific description available for this alert type.")
        alert_data['severity'] = severity_levels.get(alert_data['alert_type'], "Unknown")

        content.append(Paragraph(f"Alert Report: {alert_data['alert_type']}", styles['Title']))
        content.append(Spacer(1, 12))
        content.append(Paragraph(f"Severity: {alert_data['severity']}", styles['Normal']))
        content.append(Spacer(1, 12))
        content.append(Paragraph(f"Source IP: {alert_data['src_ip']}", styles['Normal']))
        content.append(Spacer(1, 12))
        content.append(Paragraph(f"Details: {alert_data['details']}", styles['Normal']))
        content.append(Spacer(1, 12))
        content.append(Paragraph(f"Attack Description: {alert_data['description']}", styles['Normal']))
        content.append(Spacer(1, 12))
        content.append(Paragraph(f"Alert Count: {alert_data['count']}", styles['Normal']))

        doc.build(content)

class HTMLAlertFormatter(AlertFormatter):
    def format(self, alert_data):

        descriptions = {
            "ARP Spoofing Detected": "ARP spoofing involves sending fake ARP messages over a local area network. This technique exploits the lack of authentication in the ARP protocol to link an attacker's MAC address with the IP address of a legitimate computer or server on the network.",
            "Unusual ARP Response Frequency": "An unusually high frequency of ARP responses may indicate an ongoing ARP spoofing attack, where an attacker attempts to intercept, modify, or stop data in transit.",
            "Multiple MACs Detected": "Detecting multiple MAC addresses for the same IP could indicate ARP cache poisoning, a technique used to attack a network by associating the attacker’s MAC address with the IP address of a legitimate computer or server.",
            "Potential ARP Cache Poisoning": "This alert indicates possible ARP cache poisoning, where multiple MAC addresses are associated with a single IP, potentially redirecting traffic to an attacker.",
            "DHCP Spoofing": "DHCP spoofing occurs when an attacker sends fake DHCP responses to clients, assigning them an IP address controlled by the attacker. This can lead to man-in-the-middle attacks or network disruption.",
            "Suspicious Activity": "This general alert indicates suspicious network activity that may not fit a specific attack pattern but warrants further investigation.",
            "DNS Spoofing": "DNS spoofing, or DNS cache poisoning, involves introducing corrupt DNS cache information to redirect traffic to malicious sites, facilitating phishing attacks or spreading malware.",
            "DNS Tunneling": "DNS tunneling involves encoding the data of other programs or protocols in DNS queries and responses. It can be used for malicious purposes, including data exfiltration.",
            "DDoS Attack": "A Distributed Denial of Service (DDoS) attack aims to overwhelm a targeted server, service, or network by flooding it with Internet traffic, rendering it unavailable to users.",
            "DoS Attack": "A Denial of Service (DoS) attack aims to shut down a machine or network, making it inaccessible to its intended users by overwhelming it with traffic.",
            "MITM Detected": "Man-In-The-Middle (MITM) attacks involve an attacker secretly relaying and possibly altering the communication between two parties who believe they are directly communicating with each other.",
            "Port Scanning Detected": "Port scanning is a method used by attackers to discover vulnerable services that they can potentially exploit on a networked computer.",
            "Malicious Destination IP Detected": "The system has identified a connection attempt to an IP address that is known for suspicious activities, as listed in our threat intelligence database from IOCs Feeds Platform.",
            "Malicious Source IP Detected": "A network connection was initiated from an IP address recognized for harmful activities, as listed in our threat intelligence database from IOCs Feeds Platform.",
            "Frequent DNS Queries": "A high number of DNS queries in a short period may suggest suspicious activity, such as DNS tunneling or data exfiltration.",
            "High Traffic Anomaly": "A significant increase in network traffic could indicate a potential attack, such as a DDoS, or a misconfigured network device.",
            "High Entropy DGA Domain Detected": "A domain generated by a Domain Generation Algorithm (DGA) has been detected, often used by malware to evade detection by frequently changing its domain names.",
            "HTTP Flood Detected": "An HTTP flood attack aims to overwhelm a server with HTTP requests, causing a denial of service to legitimate users.",
            "ICMP Tunneling Detected": "ICMP tunneling is a method of using ICMP packets to covertly transmit data, potentially indicating data exfiltration or covert communication channels.",
            "Frequent ICMP Packets": "An unusual number of ICMP packets could indicate network scanning or ICMP tunneling, which is often used for reconnaissance or covert communication.",
            "Unusual SMB Authentication Frequency": "A high frequency of SMB authentication attempts may suggest a brute force attack, where an attacker is attempting to guess passwords to gain access to a network.",
            "Multiple SMB Authentication Attempts": "Multiple failed SMB authentication attempts could indicate a brute force attack, where an attacker is trying to gain unauthorized access by guessing passwords.",
            "Multiple SMB Session IDs": "Multiple SMB session IDs from a single IP may indicate suspicious activity, such as an attempt to evade detection by using multiple sessions.",
            "Possible TLS MITM Detected": "Potential man-in-the-middle activity detected on a TLS connection, which could compromise the confidentiality and integrity of the encrypted communication.",
            "LLMNR Poisoning Detected": "Link-Local Multicast Name Resolution (LLMNR) poisoning is an attack where an attacker responds to LLMNR requests intended for other hosts, potentially redirecting traffic to malicious sites.",
            "NBT-NS Poisoning Detected": "NetBIOS Name Service (NBT-NS) poisoning is similar to LLMNR poisoning, where an attacker responds to NBT-NS requests, potentially redirecting traffic to malicious sites.",
            "IP Spoofing Detected": "IP spoofing involves sending packets with a false source IP address, potentially used to bypass IP-based authentication or to disguise the origin of an attack.",
            "P2P Communication Detected": "Peer-to-peer (P2P) communication detected on the network, which could be used for legitimate purposes or for malicious activities such as file sharing of illegal content.",
            "MAC Flooding Detected": "MAC flooding involves sending numerous packets to a switch, each with a different source MAC address, potentially causing the switch to enter a fail-open mode and broadcast traffic to all ports.",
            "Frequent MAC Changes Detected": "Frequent changes in MAC addresses on a network interface may indicate spoofing or a scanning tool, potentially used to evade detection or to perform reconnaissance.",
            "IP Null Scan Detected": "An IP Null scan is a type of network scan where the attacker sends packets with no TCP flags set, potentially used to identify open ports by observing the target's response.",
            "RST/FIN Flood Detected": "RST/FIN flooding involves sending a large number of TCP RST or FIN packets to a target, potentially disrupting legitimate TCP connections or exhausting resources.",
            "Possible DNS over HTTPS (DoH) Detected": "This detection indicates potential use of DNS over HTTPS (DoH), which could be used to bypass traditional DNS monitoring mechanisms and obscure DNS queries from security tools.",
            "HTTP/S Beaconing Detected": "HTTP/S beaconing involves periodic communication between a compromised device and a command and control server, often indicating malware activity and the presence of an advanced persistent threat.",
            "Tor Exit Node Traffic Detected": "Traffic to or from known Tor exit nodes has been detected, which may indicate anonymized communication often associated with malicious activity, such as browsing the dark web or bypassing censorship.",
            "Newly Registered Domain Detected": "A connection to a domain that was recently registered has been detected, which can be indicative of phishing or command-and-control (C2) domains used by attackers to evade detection.",
            "Suspicious User-Agent Detected": "A user-agent string that is uncommon or known to be associated with malicious activity has been detected in network traffic, potentially indicating the use of automated tools or malware.",
            "Suspicious Hostname Detected": "A hostname in network traffic that appears unusual or is associated with known threats has been detected, warranting further investigation for potential malicious activity.",
            "Suspicious Geo-Location Detected": "Network traffic originating from or destined to an unusual or high-risk geographic location has been detected, suggesting potential malicious activity or policy violations."
        }
        severity_levels = {
            'ARP Spoofing Detected': 'Medium',
            'Unusual ARP Response Frequency': 'Low',
            'Multiple MACs Detected': 'Low',
            'Potential ARP Cache Poisoning': 'Medium',
            'DHCP Spoofing': 'Medium',
            'Suspicious Activity': 'Low',
            'DNS Spoofing': 'Medium',
            'DNS Tunneling': 'Medium',
            'DDoS Attack': 'Critical',
            'DoS Attack': 'Critical',
            'MITM Detected': 'Critical',
            'Port Scanning Detected': 'Medium',
            'Malicious Destination IP Detected': 'High',
            'Malicious Source IP Detected': 'High',
            'Frequent DNS Queries': 'Low',
            'High Traffic Anomaly': 'High',
            'High Entropy DGA Domain Detected': 'High',
            'HTTP Flood Detected': 'High',
            'ICMP Tunneling Detected': 'High',
            'Frequent ICMP Packets': 'Low',
            'Unusual SMB Authentication Frequency': 'Medium',
            'Multiple SMB Authentication Attempts': 'Low',
            'Multiple SMB Session IDs': 'Low',
            'Possible TLS MITM Detected': 'Critical',
            'LLMNR Poisoning Detected': 'Medium',
            'NBT-NS Poisoning Detected': 'Medium',
            'IP Spoofing Detected': 'High',
            'P2P Communication Detected': 'Low',
            'MAC Flooding Detected': 'Medium',
            'Frequent MAC Changes Detected': 'Low',
            'IP Null Scan Detected': 'Medium',
            'RST/FIN Flood Detected': 'High'
        }

        alert_data['description'] = descriptions.get(alert_data['alert_type'], "No specific description available for this alert type.")
        alert_data['severity'] = severity_levels.get(alert_data['alert_type'], "Unknown")

        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    margin: 20px;
                    padding: 0;
                }}
                .container {{
                    border: 1px solid #ddd;
                    padding: 20px;
                    border-radius: 5px;
                    max-width: 600px;
                    margin: 0 auto;
                }}
                .title {{
                    font-size: 24px;
                    font-weight: bold;
                    margin-bottom: 10px;
                }}
                .subtitle {{
                    font-size: 18px;
                    margin: 10px 0;
                }}
                .description {{
                    font-size: 14px;
                    margin: 10px 0;
                }}
                .footer {{
                    font-size: 12px;
                    color: #888;
                    text-align: center;
                    margin-top: 20px;
                }}
            </style>
            <title>Alert Report</title>
        </head>
        <body>
            <div class="container">
                <div class="title">Alert Report: {alert_data['alert_type']}</div>
                <div class="subtitle">Severity: {alert_data['severity']}</div>
                <div class="subtitle">Source IP: {alert_data['src_ip']}</div>
                <div class="description"><strong>Details:</strong> {alert_data['details']}</div>
                <div class="description"><strong>Attack Description:</strong> {alert_data['description']}</div>
                <div class="description"><strong>Alert Count:</strong> {alert_data['count']}</div>
            </div>
            <div class="footer">This is an automated alert report.</div>
        </body>
        </html>
        """
        
        with open(f"alert_{alert_data['src_ip']}_{alert_data['alert_type']}.html", 'w') as file:
            file.write(html_content)

class FormatterFactory:
    @staticmethod
    def get_formatter(format_type):
        if format_type == 'CSV':
            return CSVAlertFormatter()
        elif format_type == 'JSON':
            return JSONAlertFormatter()
        elif format_type == 'PDF':
            return PDFAlertFormatter()
        elif format_type == 'HTML':
            return HTMLAlertFormatter()
        else:
            raise ValueError(f"Unknown format type: {format_type}")
